### ISSUE TITLE
Unable to add previous keymap to parse args with github action

### ISSUE THREAD

**Issue by chelming** [caksoylar/keymap-drawer#100]
Hey, 
Whenever I try to pass my previous (and adjusted) keymap with parse_args, I get a nonetype error. I'm not sure if it's about layout or config though.
```
    base = KeymapData(layers=yaml_data["layers"], combos=yaml_data.get("combos", []), layout=None, config=None)
TypeError: 'NoneType' object is not subscriptable
ERROR: parsing or drawing failed for swept-corne!
``` 

I'd like to add some offsets to the bottom two dicts: https://github.com/chelming/zmk-config/blob/d3d6232a5dd134485a089ad5ea0c37648943ac97/keymap-drawer/swept-corne.yaml

and tried doing it with the following job:
```yaml
jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      keymap_patterns: "config/*.keymap"
      config_path: "" 
      output_folder: "keymap-drawer" 
      parse_args: "swept-corne:'-b keymap-drawer/swept-corne.yaml'" 
      draw_args: ""   
```

Any insight?
