### ISSUE TITLE
Can't map "&rgb_ug RGB_COLOR_HSB(0, 0, 60)" using "raw_binding_map" on the config

### ISSUE THREAD

**Issue by Townk** [caksoylar/keymap-drawer#102]
I have a layout that uses a KD configuration with several key labels replaced with symbols. One of my [layers](https://github.com/Townk/zmk-config/blob/master/docs/corne.md#media-layer) has buttons to deal with RGB Underglow. One of the keys, is supposed to reset the Underglow to the default value I set in the config file. The layer should look like this:

![corne42-layer4-media](https://github.com/caksoylar/keymap-drawer/assets/1261/7b853011-820d-439b-99b3-1f5123c3308e)

But, if I don't do some [workaround with search and replace](https://github.com/Townk/zmk-config/blob/master/support/update-layout-maps.sh#L52) on the KD layout file, the layer look like this:

![corne42-layer4-media](https://github.com/caksoylar/keymap-drawer/assets/1261/58035030-8c7a-45f4-89ef-4407564e632d)

I define the "RGB reset" key on my layout, in [this line](https://github.com/Townk/zmk-config/blob/master/config/layout/standard_layout.dtsi#L325). For convenience, this is a snippet from my config:

```cpp
&rgb_ug RGB_RESET
```

The `RGB_RESET` I used there, is a macro defined in [another file](https://github.com/Townk/zmk-config/blob/master/config/layout/specialkeys.dtsi#L67), but its content is the following:

```cpp
// RGB Helpers
#define RGB_RESET            RGB_COLOR_HSB(0, 0, 60)
```

Like all keys I want to replace with a symbol, I defined a [`raw_binding_map` entry](https://github.com/Townk/zmk-config/blob/master/support/keymap-config.yaml#L363) to replace the RGB key with the proper asset:

```yaml
parse_config:
  raw_binding_map:
    # RGB Underglow
    "&rgb_ug RGB_COLOR_HSB(0, 0, 60)": { t: "$$mdi:palette-outline$$", h: "reset" }
```

I also tried to use the `RGB_RESET` macro:

```yaml
parse_config:
  raw_binding_map:
    # RGB Underglow
    "&rgb_ug RGB_RESET": { t: "$$mdi:palette-outline$$", h: "reset" }
```

But I think the KD preprocessor replaces it, do it does not work.

The request for this ticket is:

Is there a way to replace that key definition using `raw_binding_map`?
