### ISSUE TITLE
Feature request: toggle rendering in `ComboSpec`

### ISSUE THREAD

**Issue by rschenk** [caksoylar/keymap-drawer#104]
I have a combo that activates a layer. Since the depressed keys correctly appear styled red in the layer diagram, having the combo rendered all over the place adds a lot of clutter and is redundant, so I like to remove it.

I could manually remove the combo from the yaml output of `keymap parse` but I don't like to edit this file at all, I prefer my actual `.keymap` file to be the single source of truth so that every time I edit the keymap I can automatically generate the SVG. 

What I've been doing is this, which is a hack but works:
```yaml
# config.yaml
  zmk_combos:
    the_combo_i_want_to_skip:
      key: ""
      height: 0.01
      width: 0.01
      dendron: false
```

What would be nicer is:
```yaml
# config.yaml
  zmk_combos:
    the_combo_i_want_to_skip:
      ignore: true 

```

<details>
  <summary>Screenshot with default settings</summary>
  
![regret-default](https://github.com/caksoylar/keymap-drawer/assets/14730/8f8130b0-18f2-42df-8bf3-048529ea8720)
</details>

<details>
  <summary>Screenshot with the combo hidden</summary>
  
![regret-no-combo](https://github.com/caksoylar/keymap-drawer/assets/14730/a2135a71-c7f4-46ac-a05b-8e2fd8542a77)

</details>
