### ISSUE TITLE
[Bug] `held` property doesn't work if `raw_binding_map` use to override layer icon

### ISSUE THREAD

**Issue by dhruvinsh** [caksoylar/keymap-drawer#113]
Minimal config that breaks the `held` highlighting.

```yaml
draw_config:
  dark_mode: auto

parse_config:
  raw_binding_map:
    # Layers
    "&lt NAV ESC":
      tap: $$mdi:keyboard-esc$$
      hold: NAV
    "&lt NUM SPACE":
      tap: $$mdi:keyboard-space$$
      hold: NUM
    "&lt SYM BSPC":
      tap: $$mdi:backspace$$
```
Without `raw_binding_map`:
<img width="715" alt="image" src="https://github.com/user-attachments/assets/53b72318-67f4-48b4-99fb-b19998106403">

With `raw_binding_map`:

<img width="715" alt="image" src="https://github.com/user-attachments/assets/457a0607-1cf7-41ce-8645-545d6a3b7c8a">

**Comment by caksoylar** [comment]
The way `raw_binding_map` is used right now, it completely short circuits the usual processing if the key is found in the mapping. This includes analyzing the binding to see if it is a layer activator. I could see changing this, but I am curious if you have a practical use case for this where you'd need it, as opposed to using instead e.g. 

```yaml
parse_config:
  zmk_keycode_map:
    ESC: $$mdi:keyboard-esc$$
    SPACE: $$mdi:keyboard-space$$
```
