### ISSUE TITLE
Better layout for slanted combos

### ISSUE THREAD

**Issue by linrongbin16** [caksoylar/keymap-drawer#127]
Hi, thanks to your work! It is really useful when sharing keymap.

While I found when two keys in a combo are slanted, for example in a QWERTY standard based layout, if I have a combo `Q+S=[`, without the `seperate_combo_diagram` option.

The rendering result is:

![my_keymap](https://github.com/user-attachments/assets/9a00b8ef-d835-402e-9d6e-6e087dd326ed)

I think the rendering issue is: people cannot tell whether the combo is `Q+S` or `W+A`. Because they look the same.

Can we add some extra lookings to make it more explicit to tell user, where the combo keys are from?

The keymap yaml is:

```yaml
layout:
  qmk_keyboard: corne_rotated
  qmk_layout: LAYOUT_split_3x5_3
layers:
  DEF:
    - [Q, W, E, R, T, Y, U, I, O, P]
    - [{h: Ctrl, t: A}, {h: Gui, t: S}, {h: Alt, t: D}, {h: Shift, t: F}, G, H, {h: Shift, t: J}, {h: Alt, t: K}, {h: Gui, t: L}, {h: Ctrl, t: "'"}]
    - [Z, X, C, V, B, N, M, ",", ., /]
    - {h: Gui,   t: Tab, type: ghost}
    - {h: Ctrl,  t: Esc}
    - {h: NAV,   t: BSpace}
    - {h: SYM,   t: Space}
    - {h: Shift, t: Enter}
    - {h: Alt,   t: Delete, type: ghost}
combos:
  - {p: [0,11], k: "[", l: ["DEF"]}

```
