### ISSUE TITLE
Feature request: mouse emulation

### ISSUE THREAD

**Issue by kalbasit** [caksoylar/keymap-drawer#143]
https://github.com/zmkfirmware/zmk/pull/2477 was recently merged upstream adding support for proper mouse emulation support (movement, scrolling alongside existing clicking). It would be great to add support for it.

**Comment by caksoylar** [comment]
I agree, I should add them to the default config to be converted. Currently the problem is we have no defaults for `raw_binding_map` and I don't want to particularly add defaults there. I am planning to add a new field like `zmk_behavior_param_map` to generalize it, so you can map non-keycode parameters:

```yaml
parse_config:
  zmk_behavior_param_map:
    'mmv': { MOVE_LEFT: Mouse Left , MOVE_RIGHT: Mouse Right }
    ...
```

and we can add defaults values there.

For now, you can use `raw_binding_map` to override them, see my config as an example: https://github.com/caksoylar/zmk-config/blob/2495088f65f362700a586ee90353c29a8842c742/keymap-drawer/config.yaml#L32-L46
