### ISSUE TITLE
Feature request: view layer with ⇧.

### ISSUE THREAD

**Issue by Eh2406** [caksoylar/keymap-drawer#146]
While over engineering a key layout today, I went to add a new symbols layer. To get to the symbols layer I would hold my existing `&mo _` (where `_` is a "layers that's mostly numbers") and my dedicated Shift key. While getting all that configured, I accidentally tried typing as if it was set up. And it worked. If `&mo n + $kp N1` gives me `1` then `&kp LSHFT + &mo _ + $kp N1` gives me `!`. In retrospect that was obvious, that is what the normal keyboard does.

Without assistance, I find it tricky to learn a layout. Everyone does that's why this tool exists. Thank you for it! If I don't see `!` on my rendered cheat sheet, I would assume that it is not possible to type it with my current layout. So I would like my cheat sheet to also show "the shift modified versions of each layer", or something.

I don't know exactly what I'm asking for, some way to see "what could I type if I'd used this layer while holding this modifier". Perhaps a second copy of the keyboard for the "shift modified" symbols, in effect treating "shift + layer" as a different layer than "layer"? Or a configuration option to change what's displayed on the keyboard to shift modified of the keypress? Or cramming both symbols on the same key? (Which sounds silly but is how commercial keyboards solve the problem.)

**Comment by caksoylar** [comment]
Hi there, while parsing with default config parameters doesn't output them, there exists a `shifted` field in [the key spec](https://github.com/caksoylar/keymap-drawer/blob/main/KEYMAP_SPEC.md#layers) that is printed on the top of the key. You can see an example of them on the `. , /` keys in this keymap: https://keymap-drawer.streamlit.app/?example_yaml=showcase.yaml

So if you are manually creating a keymap YAML to draw, you can replace e.g. `"1"` legend with `{t: "1", s: !}` to remind you that you can type `!` if you use shift+1. If you are parsing a ZMK keymap, you should override [`zmk_keycode_map`](https://github.com/caksoylar/keymap-drawer/blob/main/CONFIGURATION.md#zmk_keycode_map) so that it has shifted symbols too, for example:

```yaml title=keymap_drawer.config.yaml
draw_config:
  zmk_keycode_map:
  - N1: {t: "1", s: !}
  - N2: {t: "2", s: @}
  - ... # etc.
```

**Comment by Eh2406** [comment]
Thank you. That worked like a charm. The list (or all that I have needed so far) is:

```yaml
  zmk_keycode_map:
    N1:
      t: "1"
      s: "!"
    N2:
      t: "2"
      s: "@"
    N3:
      t: "3"
      s: "#"
    N4:
      t: "4"
      s: "$"
    N5:
      t: "5"
      s: "%"
    N6:
      t: "6"
      s: "^"
    N7:
      t: "7"
      s: "&"
    N8:
      t: "8"
      s: "*"
    N9:
      t: "9"
      s: "("
    N0:
      t: "0"
      s: ")"
    EXCLAMATION: '!'
    EXCL: '!'
    AT_SIGN: '@'
    AT: '@'
    HASH: '#'
    POUND: '#'
    DOLLAR: $
    DLLR: $
    PERCENT: '%'
    PRCNT: '%'
    CARET: ^
    AMPERSAND: '&'
    AMPS: '&'
    ASTERISK: '*'
    ASTRK: '*'
    STAR: '*'
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL:
      t: "="
      s: "+"
    PLUS: +
    MINUS:
      t: "-"
      s: "_"
    UNDERSCORE: _
    UNDER: _
    SLASH:
      t: "/"
      s: "?"
    FSLH:
      t: "/"
      s: "?"
    QUESTION: '?'
    QMARK: '?'
    BACKSLASH:
      t: \
      s: '|'
    BSLH:
      t: \
      s: '|'
    PIPE: '|'
    NON_US_BACKSLASH: \
    PIPE2: '|'
    NON_US_BSLH: '|'
    SEMICOLON:
      t: ";"
      s: ":"
    SEMI:
      t: ";"
      s: ":"
    COLON: ':'
    SINGLE_QUOTE:
      t: ''''
      s: '"'
    SQT:
      t: ''''
      s: '"'
    APOSTROPHE:
      t: ''''
      s: '"'
    APOS:
      t: ''''
      s: '"'
    DOUBLE_QUOTES: '"'
    DQT: '"'
    COMMA:
      t: ","
      s: "<"
    LESS_THAN: <
    LT: <
    PERIOD:
      t: "."
      s: ">"
    DOT:
      t: "."
      s: ">"
    GREATER_THAN: '>'
    GT: '>'
    LEFT_BRACKET:
      t: "["
      s: "{"
    LBKT:
      t: "["
      s: "{"
    LEFT_BRACE: '{'
    LBRC: '{'
    RIGHT_BRACKET:
      t: "]"
      s: "}"
    RBKT:
      t: "]"
      s: "}"
    RIGHT_BRACE: '}'
    RBRC: '}'
    GRAVE:
      t: "`"
      s: "~"
    TILDE: '~'
    NON_US_HASH: '#'
    NUHS: '#'
    TILDE2: '~'
```
