### ISSUE TITLE
GitHub Workflow: provide a way to install a specific version of keymap-drawer

### ISSUE THREAD

**Issue by magicDGS** [caksoylar/keymap-drawer#154]
Currently the installation of keymap-drawer could be from source using a commit or a branch, or if none provided installing with pip the latest version.

Having a way to provide a version to the workflow that, if provided, uses  `pip install keymap-drawer==${version}` will be really good to ensure that the workflow is reproducible and works with the repository configuration.

**Comment by caksoylar** [comment]
Added it in https://github.com/caksoylar/keymap-drawer/tree/ci-install_version, can you try? e.g.

```yaml
jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@ci-install_version
    with:
      install_version: "0.19.0"
      # …other inputs
```
