### ISSUE TITLE
Improve layer activation specification, for momentary or toggled activators

### ISSUE THREAD

**Issue by caksoylar** [caksoylar/keymap-drawer#158]
Currently, we have two visualization tools that link keys to layers that they activate:

1. `held` key type, which indicates a held-down key while a layer is active
2. the hyperlink to the layer header on the activator *field* in a key, added by `draw_config.style_layer_activators`

The first one is determined by `keymap parse` (when it can, it fails for custom behaviors and customizations using `raw_binding_map`, see #113 and #157) and is reflected in the keymap YAML with the `type: held` field.

The second one on the other hand, is determined by `keymap draw` through a simple string match: it only checks if the legend field is exactly equal to one of the layer names. This cannot be specified in any way in keymap YAML or customized with `draw_config`. For instance, the detection doesn't work when you use `parse_config.layer_legend_map` to customize layer legends (#148).

I think it is inelegant and not good design to have this incongruency, where at the end of the day, both features are tying layers to the keys they activate from. Both 1. and 2. should be able to be configured in keymap YAML or `draw_config`.

Implementation alternatives: TBD

**Comment by urob** [comment]
I like adding an `activates` field as you mentioned in #148. A few more thoughts on that.

What about nesting `activates` inside a "`legends`" dictionary to track which key type does the activation. For instance,
```yml
layers:
  Base:
    # Key types map to dictionaries with a 'title' (or 'legend'?) and an optional `activates` field
    - {t: {title: StickySym, activates: Sym}, h: {title: Nav, activates: Nav}}
    
    # The current simpler syntax is remapped internally
    - {t: Q, h: Ctrl}   # Same as {t: {title: Q}, h: {title: Ctrl}}
    - W                 # Same as {t: {title: W}}
```

It would make the keymap YAML the only source of truth rather than parts of the logic being implicit in `keymap draw`. And as you said, all the activation config could be done in `raw_binding_map` without needing additional config options, which would be both cleaner and more powerful.

In terms of backwards compatibility, the current string matching logic could be moved to the parse step (if there is no `raw_binding_map` for a key)[^1]. Then the change would only be breaking for folks who map `hold` to a layer in `raw_binding_map`.

Regarding the `held` key type, it seems it would be redundant from an informational perspective. One alternative could be to remove it from the keymap YAML and replace it with a `draw_config` option that specifies for which key types, layers linked in `activates` are automatically highlighted in the drawing step.[^2] For instance,
```yml
draw_config:
  # The current default where only 'hold' key types are highlighted
  highlight_layer_activators: {hold} 
 
  # Also highlight sticky layers etc
  highlight_layer_activators: {tap, hold} 

  # Highlight layers activated by any key type
  highlight_layer_activators: {all} 
```

Similar, all hyperlinks could be added in the drawing step based of `activates`.

[^1]: For maximum backward compatibility, one could default to only match layer strings in `hold` key types, though doing this for all key types seems a more sensible default to me.

[^2]: This would be breaking in case anyone is manually using `held` to customize things. Not sure if that warrants keeping around an otherwise redundant field in the keymap YAML.
