### ISSUE TITLE
Missing combos with `--base-keymap` option and QMK keymap.json

### ISSUE THREAD

**Issue by hasssan** [caksoylar/keymap-drawer#173]
Hi caksoylar,

First, thank you for the amazing tool to create keymap visualization. It really help me learn a new keymap with visualization.

I found that a combo is missing from the generated keymap when using the `--base-keymap` option and QMK keymap.json.

My workflow is:

1. Create `base.yml` using QMK `keymap.json`
2. Modify `base.yml` to add combos because QMK `keymap.json` does not support combo.
3. Create visualization with `base.yml` without the `--base-keymap` option. Here, **combos are rendered correctly**.
3. Modify the QMK `keymap.json` file to change something unrelated to the combo.
4. Create a new visualization with `--base-keymap base.yml` option. Here, **combos are missing from the SVG file**.

Looking in the code, in [`rebase` function](https://github.com/caksoylar/keymap-drawer/blob/74a1526a6875f66378a88a1dcf2078790212d8b5/keymap_drawer/keymap.py#L221), the combo in base keymap is ignored if the current keymap does not have the combo.
I think this issue only affects QMK `keymap.json` because it does not support combo. I have no experience with ZMK.

For now, my workaround is to patch the `rebase` function to use `base_keymap.combos` if the current keymap does not have combos. [commit](https://github.com/hasssan/keymap-drawer/commit/654dad2eec30bdced0afe1e5e231bc4e767daec2)

I would like to hear your thoughts about this issue.

---

Here is a minimal code to reproduce the issue:

Modified QMK `keymap.json`:
```json
{
  "version": 1,
  "notes": "",
  "documentation": "",
  "keyboard": "4by3",
  "keymap": "custom",
  "layout": "LAYOUT_horizontal",
  "layers": [
    [
      "KC_VOLU",
      "KC_1",
      "KC_2",
      "KC_3",
      "KC_MUTE",
      "KC_4",
      "KC_5",
      "KC_6",
      "KC_VOLD",
      "KC_7",
      "KC_8",
      "KC_9"
    ]
  ],
  "author": ""
}
```

`base.yml`:
```yaml
layout: { qmk_keyboard: 4by3, layout_name: LAYOUT_horizontal }
layers:
  L0:
    - VOLU
    - { t: ▽, type: trans }
    - { t: ▽, type: trans }
    - { t: ▽, type: trans }
    - MUTE
    - MPRV
    - MPLY
    - MNXT
    - VOLD
    - { t: ▽, type: trans }
    - { t: ▽, type: trans }
    - { t: ▽, type: trans }
combos:
  - { p: [0, 1], k: "1AB", l: ["L0"] }
  - { p: [4, 8], k: "2B3C", dendron: true, l: ["L0"] }
  - { p: [0, 1, 2], k: "1ABC", a: top, arc_scale: 0.9, l: ["L0"] }
  - { p: [0, 2], k: "1AC", a: top, offset: 0.6, l: ["L0"] }
```

Parse with base keymap and modified QMK `keymap.json`:
```bash
keymap parse -b base.yml -q keymap.json > keymap.yml
```

output `keymap.yml`:
```yaml
layout: {qmk_keyboard: 4by3, layout_name: LAYOUT_horizontal}
layers:
  L0:
  - VOLU
  - {t: '1', type: trans}
  - {t: '2', type: trans}
  - {t: '3', type: trans}
  - MUTE
  - '4'
  - '5'
  - '6'
  - VOLD
  - {t: '7', type: trans}
  - {t: '8', type: trans}
  - {t: '9', type: trans}
```
