### ISSUE TITLE
[Feature] Add github workflow/action for QMK

### ISSUE THREAD

**Issue by samuelborn** [caksoylar/keymap-drawer#177]
The project has a predefined github workflow/action for ZMK.
I did not find anything similar for QMK. Would be nice to have!

**Comment by caksoylar** [comment]
I agree, though I haven't kept up to date with QMK userspace work much. Planning to look at it sometime, eee #168.

**Comment by SamuelBorn** [comment]
I just hacked together a super-minimal version for my personal repo. Obviously, it would need to be adapted to be more general, but it might be a good reference as a starting point.

```yaml
name: Visualize Keymap

on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: pip install keymap-drawer
      - uses: actions/checkout@v4
        with:
          repository: qmk/qmk_firmware
          submodules: true
      - run: docker pull ghcr.io/qmk/qmk_cli
      - uses: actions/checkout@v4
        with:
          path: keyboards/totem
      - run: docker run -v .:/qmk_firmware ghcr.io/qmk/qmk_cli qmk c2json -kb totem -km default > keymap.json
      - run: keymap parse -q keymap.json > keymap.yaml
      - run: keymap draw keymap.yaml > keyboards/totem/keymap.svg
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          repository: keyboards/totem
          commit_message: "docs: auto update keymap.svg"
```

Unfortunately, we cannot execute our commands directly in the official QMK Docker container as it is done [in the official docs](https://docs.qmk.fm/newbs_building_firmware_workflow#add-a-github-action-workflow) because the Python version in there is only 3.9, which your project no longer supports.

My script expects the GitHub repo to be able to be placed into `QMK_FIRMWARE_DIR/keyboards/REPO`. Take a look at [my repo](https://github.com/SamuelBorn/qmk-keymap) for the expected structure.

Also, the `- run: docker pull ghcr.io/qmk/qmk_cli` command is not really needed, as `docker run` would also take care of pulling the image. However, this reduces the time between the repo checkout and the SVG commit, which lessens the risk of other commits happening in the meantime.
