### ISSUE TITLE
Question: Missing shifted when parsing from qmk JSON

### ISSUE THREAD

**Issue by haunt98** [caksoylar/keymap-drawer#35]
I use qmk parse to generate yaml from my qmk JSON here https://github.com/haunt98/qmk_keymaps/blob/main/dztech_dz60rgb_wkl/keymaps_json/haunt98/keymap.json

The first row of first layout is generated:

```txt
  - QK GESC
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '0'
  - '-'
  - '='
  - \
  - '`'

```

As you can see, `-` having no shifted.

Is this epxecting feature, should I custom YAML file myself?

**Comment by caksoylar** [comment]
Currently number/symbol keycodes don't create a shifted field by default. You can tweak this by creating/modifying the config file and editing a `parse_config.qmk_keycode_map` field. Below is the default mapping, I changed `MINS` below (which corresponds to `KC_MINS`) to add the shifted field as an example:
```yaml
parse_config:
  qmk_keycode_map:
    XXXXXXX: ''
    'NO': ''
    MINUS: '-'
    MINS: {t: '-', s: '_'}  # modified
    EQUAL: '='
    EQL: '='
    LEFT_BRACKET: '['
    LBRC: '['
    RIGHT_BRACKET: ']'
    RBRC: ']'
    BACKSLASH: \
    BSLS: \
    NONUS_HASH: '#'
    NUHS: '#'
    SEMICOLON: ;
    SCLN: ;
    QUOTE: ''''
    QUOT: ''''
    GRAVE: '`'
    GRV: '`'
    COMMA: ','
    COMM: ','
    DOT: .
    SLASH: /
    SLSH: /
    TILDE: '~'
    TILD: '~'
    EXCLAIM: '!'
    EXLM: '!'
    AT: '@'
    HASH: '#'
    DOLLAR: $
    DLR: $
    PERCENT: '%'
    PERC: '%'
    CIRCUMFLEX: ^
    CIRC: ^
    AMPERSAND: '&'
    AMPR: '&'
    ASTERISK: '*'
    ASTR: '*'
    LEFT_PAREN: (
    LPRN: (
    RIGHT_PAREN: )
    RPRN: )
    UNDERSCORE: _
    UNDS: _
    PLUS: +
    LEFT_CURLY_BRACE: '{'
    LCBR: '{'
    RIGHT_CURLY_BRACE: '}'
    RCBR: '}'
    PIPE: '|'
    COLON: ':'
    COLN: ':'
    DOUBLE_QUOTE: '"'
    DQUO: '"'
    DQT: '"'
    LEFT_ANGLE_BRACKET: <
    LABK: <
    LT: <
    RIGHT_ANGLE_BRACKET: '>'
    RABK: '>'
    GT: '>'
    QUESTION: '?'
    QUES: '?'
```

Then you would use it with `keymap -c config.yaml parse -q keymap.json >keymap.yaml` etc., or paste it in the "Configuration" box at the bottom of the web app.
