### ISSUE TITLE
Feature request: export layout config for the GitHub action

### ISSUE THREAD

**Issue by dhruvinsh** [caksoylar/keymap-drawer#47]
While using the keymap-drawer action, if the `draw_args` are provided for type of keyboard or layout as a override, can we please put this details in the `keyboard.yaml` file in the output folder.

```
      draw_args: "lynx:'-k ferris/sweep -l LAYOUT_split_3x5_2'"
```
would have output in lynx.yaml config as
```yaml
layout:
  qmk_keyboard: ferris/sweep
  qmk_layout: LAYOUT_split_3x5_2
```

This way I can just use the whole config file in the online svg editor.
