### ISSUE TITLE
Feature request: show us intl keys

### ISSUE THREAD

**Issue by mknj** [caksoylar/keymap-drawer#50]
I am using a us-intl layout on windows and linux and i am missing letters like Ö, Ñ and Ø in the drawings.

I would like to see a blue layer like here: https://en.wikipedia.org/wiki/QWERTY#/media/File:KB_US-International.svg

Bonus: Ideally you could also specify that you are using i.e. a spanish, french or german layout and then the output is adapted to that language.

**Comment by caksoylar** [comment]
I think this is a duplicate of #32, except for the bonus section. That would require shipping data files that contain display forms of various keyboard layouts. Perhaps it would be possible by automatically parsing cldr files similar to https://github.com/joelspadin/zmk-locale-generator, while extracting shift/ralt keycodes.

**Comment by MattSturgeon** [comment]
Re: the bonus section, it is relatively simple to simply re-implement the `zmk_keycode_map` or `qmk_keycode_map` in your config. For example I've [done this in my config](https://github.com/MattSturgeon/Glove80-Config/blob/6be8debed9bba1107392ef65004dc75df97ac9f2/config/keymap_drawer.yaml#L187) in order to draw the UK layout.

**Comment by paoloantinori** [comment]
Hi there. I'm experimenting with this feature, since the current behavior generates really ugly looking images on my setup:

https://github.com/paoloantinori/zmk-config-zen-2/raw/uk/keymap-drawer/corneish_zen.svg?raw=true

So far I've found that a funny improvement is to just make the `zmk-locale-generator` generated headers unavailable.
If that happens, instead of resolving the definitions, the original key is maintained, which is already a good improvement, moving from this:

```yaml
layers:
  BASE:
  - - {t: '(ZMK HID USAGE(HID USAGE KEY, HID USAGE KEY KEYBOARD Q))', h: ESC}
    - {t: '(ZMK HID USAGE(HID USAGE KEY, HID USAGE KEY KEYBOARD W))', h: TAB}
    - (ZMK HID USAGE(HID USAGE KEY, HID USAGE KEY KEYBOARD E))
    - (ZMK
```

to this:

```yaml
layers:
  BASE:
  - - {t: GB Q, h: ESC}
    - {t: GB W, h: TAB}
    - GB E
    - GB R
```

Just to make a little progress here I've even added an extra config param to `keymap-drawer`:

```yaml
parse_config:
  remove_prefixes:
    - "GB"
```

just to simplify the manipulation that led me to this output:

```yaml
layers:
  BASE:
  - - {t: ' Q', h: '$$mdi:keyboard-esc$$'}
    - {t: ' W', h: '$$mdi:keyboard-tab$$'}
    - ' E'
    - ' R'
```

with a very acceptable improvement over the output:

https://github.com/paoloantinori/zmk-config-zen-2/blob/visual_editor/keymap-drawer/corneish_zen.svg



But, I was hoping to have a real permanent solution to this approach and I've got a tip from @nickcoutsos who nicely shared his pre processing approach:

https://github.com/nickcoutsos/keymap-editor/discussions/141#discussioncomment-7492891

I've managed to have his script working, so I see a path for a smart detection and delegation of the parsing logic to `zmk-locale-generator` libraries to avoid rewriting code from scratch.

I stopped here and decided to ask for feedback on this thread because `zmk-locale-generator` seems not to be a published dependency and I have no idea what could be the best course of action to consume those modules from withing this project.

Open to any feedback!
