### ISSUE TITLE
View is cut off when combo description is offset

### ISSUE THREAD

**Issue by anarion80** [caksoylar/keymap-drawer#70]
I have my combo offset like this:

```yaml
 zmk_combos:
    combo_mouse:
      align: top
      offset: 0.4
```

and the resulting SVG is cut off at the top:
![obraz](https://github.com/caksoylar/keymap-drawer/assets/2185791/04c4ed86-1a3e-4d95-b07f-6df9dc9043fe)

Is there a way to calculate the viewBox correctly with this or at least add some manual offset?
