### ISSUE TITLE
Pull in symbols for numbers automatically from zmk config

### ISSUE THREAD

**Issue by griccardos** [caksoylar/keymap-drawer#93]
when reading `number_1`, `number_2` etc. from zmk config, only the numbers are pulled in ('1', '2' etc.) and only those are shown in the image.
One needs to change the yaml `'1'` to `{t:'1' , s:'!'}` everytime one pulls in a config file for each number
Have an option for automatically pulling in the symbols for `number_0` to `number_9` or maybe an option for showing the symbols above

**Comment by caksoylar** [comment]
Hey, just to make sure you are aware of it, overrides can be set in the [`parse_config.zmk_keycode_map`](https://github.com/caksoylar/keymap-drawer/blob/main/CONFIGURATION.md#zmk_keycode_map) configuration, which is under the "Raw configuration" box in the web app. So e.g. you could write the following:

```yaml
parse_config:
  # ...other items
  zmk_keycode_map:
    # ...existing default values
    N1: {t: 1, s: "!"}
    N2: {t: 2, s: "@"}
    # ...etc
```

This way you can parse keymaps multiple times and the substitution will happen automatically. (Configuration isn't persisted across page reloads, so you might want to keep a copy of it somewhere for the next time you'll use the web page.)

I previously thought about just adding these to the default map values; there isn't much downside to that except that it is a breaking change. One issue is that the shifted number values can be different for different locales, but that's probably fine for now. What do you think?
