### ISSUE TITLE
Feature request: Display multiple keys that could activate a layer

### ISSUE THREAD

**Issue by calummm** [caksoylar/keymap-drawer#98]
Currently there appears to be a way to show each layer with the corresponding key or multiple keys required to press to activate that layer but no way to show an OR situation. I am experimenting with having multiple ways to activate a layer, in this case either thumb can activate each layer. 

Perhaps we could show this with different colors or textures so as not to confuse.

## Currently:
![image](https://github.com/caksoylar/keymap-drawer/assets/4608505/f3f95b3b-3edc-42ed-9aa8-8217032c8412)

## Possible solution:
![image](https://github.com/caksoylar/keymap-drawer/assets/4608505/d2d707d6-52d2-41fb-86bf-f6caabca36bc)

**Comment by caksoylar** [comment]
Hi, this is possible via the `mark_alternate_layer_activators` setting: https://github.com/caksoylar/keymap-drawer/blob/main/CONFIGURATION.md#mark_alternate_layer_activators

It's an interesting idea to denote them with a different color, since that'd resolve the ambiguity of the AND vs. OR situation. I suspect it might not be clear on first glance what the different color means, but let me think about that.

**Comment by calummm** [comment]
Yes, I can see how it is confusing with two of the same color as I do use that for a special layer activation. Is there an exposed style selector I might be able to override? Perhaps nth child?

Thank you for the tip about dark mode.

**Comment by caksoylar** [comment]
You can always go by key position + layer, like `.layer-DEF .keypos-33 > rect { fill: blue; }` for 34th key on layer `DEF`. (I think it should be possible to select nth child with class `.held` as well but my CSS skills seem lacking for that.)

I'll try to add a tweak to parsing to add a special type like `"held alternate"` so you can override it in the CSS (and it will still default to `held` styling otherwise). We can consider whether we adjust the default style for it later.

**Comment by caksoylar** [comment]
I added this in 1b99a076ef43d87e7ebb1929cd133e6daf8a06d9, can you give it a try? You can use it with a new CSS override like
```yaml
draw_config:
  svg_extra_style: "rect.held.alternate { fill: purple; }"
```

**Comment by calummm** [comment]
I was hoping I would be able to trigger this via workflow but cannot seem to. 
Tried using:

```yml
jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@1b99a076ef43d87e7ebb1929cd133e6daf8a06d9
```
Will setup keymap-drawer locally later and try your change

**Comment by caksoylar** [comment]
Instead of that, try using this:
```yaml
jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    with:
      install_branch: main  # install git version from main branch, not pypi
```

**Comment by calummm** [comment]
Finally got it working with
```yml
jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@1b99a076ef43d87e7ebb1929cd133e6daf8a06d9
    with:
      install_branch: 1b99a076ef43d87e7ebb1929cd133e6daf8a06d9 
```

Looks like it works well, tyvm. I'm not sure if we would need to account for light/dark mode? Probably I need to write a better selector. This is with `fill: #478583`

![image](https://github.com/caksoylar/keymap-drawer/assets/4608505/291296e9-d194-4706-b40e-a14029355075)

**Comment by caksoylar** [comment]
Thanks for confirming.

> Finally got it working with

I'd have expected my example to work, it's weird if it didn't.

You can override the dark mode CSS separately like this if you like:

```yaml
draw_config:
  svg_extra_style: |
    rect.held.alternate { fill: #478583; }
    @media (prefers-color-scheme: dark) { rect.held.alternate { fill: #478583; } }  # some other color here
```
